import = [
    "~/.config/alacritty/tokyonight_storm.toml"
]

[window]
opacity = 0.95
startup_mode = "Maximized"
decorations = "None"

[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Semi Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Italic" }
size = 9.35

