"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2

[[blocks]]
type = "rprompt"

  [[blocks.segments]]
  foreground = "#007ACC"
  template = " {{ .CurrentDate | date .Format }} "
  style = "plain"
  type = "time"

    [blocks.segments.properties]
    time_format = "15:04:05"

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
  type = "session"
  template = "{{ if .SSHSession }}REMOTE{{ end }}"
  style = "plain"
  foreground = "#ffe781"

  [[blocks.segments]]
  type = "session"
  template = "@{{ .UserName }}"
  style = "plain"
  foreground = "#93e97f"


  [[blocks.segments]]
  type = "path"
  style = "plain"
  foreground = "#a06cff"
  template = " \uf07b {{ .Path }} "

    [blocks.segments.properties]
    style = "agnoster_full"

  [[blocks.segments]]
  foreground = "#2e9599"
  foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#f79a67{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#a8216b{{ end }}",
  "{{ if gt .Ahead 0 }}#35b5ff{{ end }}",
  "{{ if gt .Behind 0 }}#f89cfa{{ end }}"
]
 
template = "{{ .UpstreamIcon }}{{ .HEAD }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }} |  {{ .StashCount }}{{ end }}"
  style = "plain"
  type = "git"

    [blocks.segments.properties]
    branch_max_length = 25
    fetch_status = true
    fetch_upstream_icon = true

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  template = "$"
  foreground = "#F5BDE6"

